baseurl = "https://igarycc.github.io/" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "Hwa Nan Alumnae Inc"
theme = "hugo-universal-theme"
themesDir = "./themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]


# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/img/home_dropdown.jpg"
    weight     = 1

[[menu.main]]
    name       = "About"
    identifier = "section.about"
    url        = ""
    weight     = 1
    parent     = "menu.home"
    post       = 1

[[menu.main]]
    name       = "Introduction"
    identifier = "section.intro"
    url        = ""
    weight     = 2
    parent     = "menu.home"
    post       = 1

[[menu.main]]
    name       = "Study Abroad"
    identifier = "section.study-abroad"
    url        = ""
    weight     = 1
    parent     = "menu.home"
    post       = 2

[[menu.main]]
    name       = "About Us"
    url        = "/about-us/"
    weight     = 1
    parent     = "section.about"

[[menu.main]]
    name       = "Our History"
    url        = "/history/"
    weight     = 1
    parent     = "section.intro"

[[menu.main]]
    name       = "Present and Future"
    url        = "https://lily36520.wixsite.com/hwa-nan-alumnae-inc/present-and-future"
    weight     = 2
    parent     = "section.intro"

[[menu.main]]
    name       = "Alumnae Activities"
    url        = "https://lily36520.wixsite.com/hwa-nan-alumnae-inc/alumnae-activities"
    weight     = 3
    parent     = "section.intro"

[[menu.main]]
    name       = "History of International Exchanges"
    url        = "/study-abroad/international-exchange-history/"
    weight     = 1
    parent     = "section.study-abroad"

[[menu.main]]
    name       = "University of Puget Sound"
    url        = "/study-abroad/puget-sound/"
    weight     = 2
    parent     = "section.study-abroad"

[[menu.main]]
    name       = "Centenary University"
    url        = "/study-abroad/centenary/"
    weight     = 3
    parent     = "section.study-abroad"

[[menu.main]]
    name       = "Morningside College"
    url        = "/study-abroad/morningside/"
    weight     = 4
    parent     = "section.study-abroad"

[[menu.main]]
    name       = "Emporia State University"
    url        = "/study-abroad/emporia-state/"
    weight     = 5
    parent     = "section.study-abroad"


# [[menu.main]]
#     name       = "Blog"
#     identifier = "menu.blog"
#     url        = "/blog/"
#     weight     = 5

[[menu.main]]
    name       = "News & Events"
    identifier = "menu.news"
    url        = "/news/"
    weight     = 5

[[menu.main]]
    name       = "Recruitment"
    identifier = "menu.recruitment"
    url        = "/recruitment/"
    weight     = 6

[[menu.main]]
    name       = "Donation"
    identifier = "menu.donation"
    url        = "/donation/"
    weight     = 7

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 8


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+86 XXXXXXXXXXX"
    pre = "<i class='fas fa-2x fa-phone'></i>"

# [[menu.topbar]]
#     weight = 2
#     name = "GitHub"
#     url = "https://github.com/devcows/hugo-universal-theme"
#     pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:hwananalumnaeinc@gmail.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/news/"     # [GaryC] it seems that this config is never used
    author = "Hwa Nan Alumnae Inc"
    defaultKeywords = ["Hwa Nan", "Alumnae"]
    mainSections = ["news", "study-abroad"]         # [GaryC] removed from mainSections: ["blog"]
    defaultDescription = "Hwa Nan Alumnae Inc Official Website"

    # Social media
    # [GaryC] TODO: 填参数
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.jpg"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "violet"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>这是一个placeholder。在这里写一句话介绍华南校友会。</p>"
    copyright = "© 2024, Hwa Nan Alumnae Inc. All Rights Reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Hwa Nan Alumnae Inc"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Hwa Nan Alumnae Inc.</strong>
        <br>在这里
        <br>写上
        <br>组织的
        <br>详细的
        <br>
        <strong>地址信息</strong>
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on +86 XXXXXXXXXXX or hwananalumnaeinc@gmail.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+86 XXXXXXXXXXX" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hwananalumnaeinc@gmail.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 4 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "List of Presidents"
    subtitle = "【此行可替换或删除】这里可以放院长简介"

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "Check our cloud-archived documents. Access permission may be required."
    link_url = "https://drive.google.com/drive/folders/1Dv6ZIWxzNbRYT_5JoVsof4PfeB621Uwh"
    link_text = "Archived Docs"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Partners & Sponsors"
    subtitle = "这里可以放一些合作伙伴 / 赞助商的 logo & 链接。如不需要可整块删除。"

[params.recent_posts]
    enable = true
    title = "Recent News & Events"
    subtitle = "【小标题，可删除或更换】这里是 Recent News & Events 的相关文章"
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
